// Generated by CoffeeScript 1.10.0
(function() {
  var BrowserWindow, app, mainWindow;

  app = require('app');

  BrowserWindow = require('browser-window');

  mainWindow = null;

  app.on('window-all-closed', function() {
    return app.quit();
  });

  app.on('ready', function() {
    mainWindow = new BrowserWindow({
      width: 640,
      height: 480
    });
    mainWindow.loadUrl('file://' + __dirname + '/index.html');
    return mainWindow.on('close', function() {
      return mainWindow = null;
    });
  });

}).call(this);
