// Generated by CoffeeScript 1.10.0
(function() {
  window.onload = function() {
    var main_video, scale;
    navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;
    main_video = document.getElementById('main');
    navigator.getUserMedia({
      video: true
    }, function(stream) {
      console.log(stream);
      main_video.src = window.URL.createObjectURL(stream);
      return main_video.play();
    }, function(error) {
      alert(error);
      return console.error(error);
    });
    scale = document.getElementById('scale');
    return scale.oninput = function() {
      return main_video.style.transform = 'scale(' + scale.value + ')';
    };
  };

}).call(this);
