// Generated by CoffeeScript 1.10.0
(function() {
  window.onload = function() {
    var video;
    navigator.getUserMedia = navigator.getUserMedia || navigator.webkitGetUserMedia || navigator.mozGetUserMedia || navigator.msGetUserMedia;
    video = document.getElementsByTagName('video')[0];
    return navigator.getUserMedia({
      video: true
    }, function(stream) {
      console.log(stream);
      video.src = window.URL.createObjectURL(stream);
      return video.play();
    }, function(error) {
      alert(error);
      return console.error(error);
    });
  };

}).call(this);
